kind: pipeline
name: default

trigger:
  branch:
  - master
  - 1.0.0.RELEASE
  event:
  - push

steps:

#- name: code-analysis
#  image: 192.168.110.129:5000/aosapps/drone-sonar-plugin:latest
#  pull: IfNotPresent
#  extra_hosts:
#    - "sonar.yizhishang.com:192.168.110.129"
#  settings:
#    sonar_host: http://sonar.yizhishang.com
#    sonar_token: 2015c55e0e65f0d4145dd1b8a9d8fff4d8b73be5
#    level: debug
#    showProfiling: true

- name: build-settings
  image: docker-registry.yizhishang.com/knives/drone-maven-setting:latest
  settings:
    servers:
    - id: maven-public
      username: admin
      password: root
    - id: maven-releases
      username: admin
      password: root
    - id: maven-snapshots
      username: $${env.USERNAME}
      password: $${env.PASSWORD}
    mirrors:
    - id: maven-public
      url: http://nexus.yizhishang.com/repository/maven-public/
      mirrorOf: central

- name: maven
  image: docker-registry.yizhishang.com/maven:3-jdk-8
  pull: IfNotPresent
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
  volumes:
  - name: MavenCache
    path: /drone/src/repo
  commands:
    - mvn clean deploy -s settings.xml -DskipTests -U
  when:
    event: push
  depends_on:
  - build-settings

- name: docker
  image: docker-registry.yizhishang.com/plugins/docker:latest
  pull: IfNotPresent
  privileged: true
  settings:
    registry: docker-registry.yizhishang.com
    insecure: true
    username:
      from_secret: username
    password:
      from_secret: password
    repo: docker-registry.yizhishang.com/yizhishang/tx-manager
  when:
    event: push
  depends_on:
  - maven

volumes:
- name: MavenCache
  host:
    path: /mnt/tmp/maven
