kind: pipeline
#type: exec
name: default

trigger:
  branch:
  - master
  - gpo-tx-lcn
  - feature/*
  event:
#  - tag
  - push

steps:

- name: code-analysis
  image: 192.168.110.129:5000/aosapps/drone-sonar-plugin:latest
  pull: IfNotPresent
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
    level: debug
    showProfiling: true

- name: build-settings
  image: 192.168.110.129:5000/knives/drone-maven-setting:latest
  settings:
    servers:
    - id: maven-public
      username: admin
      password: root
    - id: maven-releases
      username: admin
      password: root
    - id: maven-snapshots
      username: $${env.USERNAME}
      password: $${env.PASSWORD}
    profiles:
    - id: drone
      properties:
        dockerHost: http://192.168.110.129:2375
        registryPrefix: yizhishang
        registryUrl: 192.168.110.129:5000
    mirrors:
    - id: maven-public
      url: http://192.168.110.129:8091/repository/maven-public/
      mirrorOf: central
    active_profiles:
      - drone
#  when:
#    event: push

- name: maven
  image: 192.168.110.129:5000/maven:3-jdk-8
  pull: IfNotPresent
  extra_hosts:
    - "nexus.yizhishang.com:192.168.110.129"
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
  volumes:
  - name: MavenCache
    path: /drone/src/repo
  commands:
    - cat settings.xml
    - mvn clean deploy -s settings.xml -DskipTests -U
  when:
    event: push
#  depends_on:
#    - build-settings

- name: docker
  image: 192.168.110.129:5000/plugins/docker:latest
  pull: IfNotPresent
  privileged: true
  settings:
    registry: 192.168.110.129:5000
    insecure: true
    username:
      from_secret: username
    password:
      from_secret: password
    repo: 192.168.110.129:5000/yizhishang/tx-manager
    dockerfile: ./Dockerfile
  when:
    event: push
#  depends_on:
#    - maven

volumes:
- name: MavenCache
  host:
    path: /mnt/tmp/maven
