apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ include "tx-manager.name" . }}
    helm.sh/chart: {{ include "tx-manager.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tx-manager.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "tx-manager.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: server-port
              containerPort: {{ .Values.service.serverPort.internalPort }}
              protocol: TCP
            - name: tx-manage-port
              containerPort: {{ .Values.service.txManagePort.internalPort }}
              protocol: TCP
          env:
            - name: tx-lcn.manager.host
              value: {{ .Values.environment.txLcn.manager.host | quote }}
            - name: tx-lcn.manager.adminKey
              value: {{ .Values.environment.txLcn.manager.adminKey | quote }}
            - name: spring.redis.host
              value: {{ .Values.environment.spring.redis.host | quote }}
            - name: spring.redis.port
              value: {{ .Values.environment.spring.redis.port | quote }}
            - name: spring.redis.database
              value: {{ .Values.environment.spring.redis.database | quote }}
            - name: spring.datasource.driver-class-name
              value: {{ .Values.environment.spring.datasource.driverClassName | quote }}
            - name: spring.datasource.url
              value: {{ .Values.environment.spring.datasource.url | quote }}
            - name: spring.datasource.username
              value: {{ .Values.environment.spring.datasource.username | quote }}
            - name: spring.datasource.password
              value: {{ .Values.environment.spring.datasource.password | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.serverPort.internalPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.serverPort.internalPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
