apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    name: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.serverPort}}
      protocol: TCP
      name: http-web
    - port: {{ .Values.service.txManagePort}}
      protocol: TCP
      name: tcp-tx
  selector:
    app.kubernetes.io/name: {{ include "tx-manager.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
